log_all: True
sampler: null
dataset: "cora"
num_repeats: 5
n_epoch: 200
patience: 20
hidden_channels: 128
num_layers: 2
dropout: 0.4
lr: 0.01
lp_hop: 2
lp_min_seeds: 3
entropy_threshold: 0.1
weight_decay: 0.0
sampler: null
unknown_class_ratio: 0.2
geometric_loss_weight: 0.1
num_protos: 7
model: "pown"
gpu_number: 0
fold_type: "disjunct"
sup_temp : 0.1
pseudo_temp : 0.7